
//! Autogenerated weights for `pallet_chess`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-11-30, STEPS: `1248`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `bernardo-benchmarking`, CPU: `AMD EPYC 7B13`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// pallet_chess
// --extrinsic
// *
// --steps
// 1248
// --repeat
// 20
// --output
// weight.rs
// --json-file=benchmarks.json

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

pub trait WeightInfo {
	fn create_match() -> Weight;
	fn abort_match() -> Weight;
	fn join_match() -> Weight;
	fn make_move() -> Weight;
}

/// Weight functions for `pallet_chess`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: Chess NextNonce (r:1 w:1)
	// Storage: Chess Matches (r:0 w:1)
	// Storage: Chess MatchIdFromNonce (r:0 w:1)
	fn create_match() -> Weight {
		Weight::from_ref_time(59_450_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(3 as u64))
	}
	// Storage: Chess Matches (r:1 w:1)
	// Storage: Chess MatchIdFromNonce (r:0 w:1)
	fn abort_match() -> Weight {
		Weight::from_ref_time(51_570_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Chess Matches (r:1 w:1)
	fn join_match() -> Weight {
		Weight::from_ref_time(49_700_000 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: Chess Matches (r:1 w:1)
	fn make_move() -> Weight {
		Weight::from_ref_time(50_133_104 * 3 as u64)
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
}

impl WeightInfo for () {
	// Storage: Chess NextNonce (r:1 w:1)
	// Storage: Chess Matches (r:0 w:1)
	// Storage: Chess MatchIdFromNonce (r:0 w:1)
	fn create_match() -> Weight {
		Weight::from_ref_time(59_450_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(3 as u64))
	}
	// Storage: Chess Matches (r:1 w:1)
	// Storage: Chess MatchIdFromNonce (r:0 w:1)
	fn abort_match() -> Weight {
		Weight::from_ref_time(51_570_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(2 as u64))
	}
	// Storage: Chess Matches (r:1 w:1)
	fn join_match() -> Weight {
		Weight::from_ref_time(49_700_000 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
	// Storage: Chess Matches (r:1 w:1)
	fn make_move() -> Weight {
		Weight::from_ref_time(50_133_104 * 3 as u64)
			.saturating_add(RocksDbWeight::get().reads(1 as u64))
			.saturating_add(RocksDbWeight::get().writes(1 as u64))
	}
}
